language: java

sudo: false

script: "mvn package --settings travis/settings.xml"

dist: trusty

jdk:
  - oraclejdk8

env:
  global:
  - secure: "s9l+WWrdHc/Be0bRhEEfnUpVd8ld4p7eQ0De64JMEURmaK3y4Acdp+32/6bKqk/9vK6GsFHi2pWH9mGua510mrAPeI4AsSWuwD73zuzBWB3bFS+Iy5xh7gQ3r1e+QSiPqPFhr9Y/Cu9Ge2NJh5WKsiT4/pwKm6lsl9y+9/sjji1/GfS6OaHZcZTZnqjN3LweI7lCyR925eRA+dX6UQN54j8s6tclalHyhN5WkrbHnPsGAOWuh2mv5eo0XRj25pzKKDKo8B6HQVR2ubZl81haTLDURXmsk0ftXjCBdtPYFHYPXr8gR837x+bzdAC6Gmqb7QaoZ1Plpert/M+QFKx0qgTnyJ/YQsRSNBzo/oxElY2twsqk54ifbDGyOsu+MYWZ+nKE4U9hSzyj2OT6b8SpqRTA9tQrZNNNYbSaceHTRwx+7SBFPMYZSgFBgPn/znWf5FQo0nSiWGbbqtEm7nYNpZVK6kUtGphYyfGg/khUhmGzqKQZNi1gCJG7JrWmbDUdLBF7rcx4pHGAjSJm6QR2B4OKiwY8UA6aH+WB7tKAaWf74IV2YjgmMpto6zT3CMVyrK2XwOqbjuOkAQWHGGuMnK0iFQf0m1U45agjB2Co5GXJ2VGKvzJSweDw2zkst8VR9isVXNpItZeY8O1DidslWChV5TsXhbOc0Q44l17LGVE="
  - secure: "W4Swp8I0uOIz5unzQwXWuKCoR0hN1V4XL5I3W560eCB1jSwCrZtOGyQgt8sSaf/M+U3igBjUef0YadUbNxwABq3qRrfwOrMiA0F85fFwLcOjo3rmegjhkACoKX6k+5q/tqSq9nw0CadsCkB4PejM38c6+zjt/NR4hAe7x5pZrNB0OKbSBQtuxwotBhV2U6F+45Wy8acItkXIMKmOdouH/x1+4nX8yEvcKy8U2QEHqhta6/g6d35osvCBy0AU9NCU6egTnlHSiO2Yhe1F5hipRCpDaBk+OE5kEsfShjsvjWrZOLOS/JZlDXNS9p+JJ6aM79QIMk91e/Oa4WSjGuZzSQuY0P9DFWVeJHh7nL+7xcxEJ6JNLsjMwHI+s1Yj6MWl18+vgfSluwIXDc2PvmQUqHHhH3nciuPbelocBHRFBvsfwh0l9133gvnVYvaKFJXrmw47Bi+3KJGhnUY6nZ9pGq1DM/k/DHd2hzR6RypjoeHPHDWNe2DB/aOXiE+nK6qfp/Sit6z3qsFZVw5nfnCd//jCkL3wGqSZc5Ic91I0pdJZOTnK963b/VEQoWx3azsTRXCiYvsOdw/oGi2co8EGDlVfjkxFJfpWK2O/HW07hzsfRtTW8dYssRM1LAAgblyBb+0j0gQCQ1yOUyabEfJcNHWGsUqZpzy+fRyPDdQm6tc="

after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
