name: Java CI

env:
  JDK_CURRENT: 17.0.9+8
  DISTRIBUTION: zulu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up JDK
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Cache Maven dependencies
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B clean install

  deploy:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up JDK
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
          server-id: sonatype-nexus-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy to Sonatype
        run: mvn -B -DskipTests deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PWD }}
